//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonPropertyAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonPropertyAnalyzer.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonPropertyAttributes to all properties in class (Newtonsoft).
        /// </summary>
        internal static string NewtonsoftJsonClassCodeFixTitle {
            get {
                return ResourceManager.GetString("NewtonsoftJsonClassCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonIgnore to property (Newtonsoft).
        /// </summary>
        internal static string NewtonsoftJsonIgnoreCodeFixTitle {
            get {
                return ResourceManager.GetString("NewtonsoftJsonIgnoreCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonPropertyAttribute to property (Newtonsoft).
        /// </summary>
        internal static string NewtonsoftJsonPropertyCodeFixTitle {
            get {
                return ResourceManager.GetString("NewtonsoftJsonPropertyCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonPropertyNameAttributes to all properties in class (System.Text.Json).
        /// </summary>
        internal static string SystemTextJsonClassCodeFixTitle {
            get {
                return ResourceManager.GetString("SystemTextJsonClassCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonIgnore to property (System.Text.Json).
        /// </summary>
        internal static string SystemTextJsonIgnoreCodeFixTitle {
            get {
                return ResourceManager.GetString("SystemTextJsonIgnoreCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonPropertyNameAttribute to property (System.Text.Json).
        /// </summary>
        internal static string SystemTextJsonPropertyCodeFixTitle {
            get {
                return ResourceManager.GetString("SystemTextJsonPropertyCodeFixTitle", resourceCulture);
            }
        }
    }
}
