//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonPropertyAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonPropertyAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonPropertyAttributes to all properties in class..
        /// </summary>
        internal static string NewtonsoftJsonClassDescription {
            get {
                return ResourceManager.GetString("NewtonsoftJsonClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; doesn&apos;t use JsonPropertyAttributes on every property.
        /// </summary>
        internal static string NewtonsoftJsonClassMessageFormat {
            get {
                return ResourceManager.GetString("NewtonsoftJsonClassMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all Properties in a class have a JsonPropertyAttribute.
        /// </summary>
        internal static string NewtonsoftJsonClassTitle {
            get {
                return ResourceManager.GetString("NewtonsoftJsonClassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonIgnore to property (Newtonsoft.Json)..
        /// </summary>
        internal static string NewtonsoftJsonIgnoreDescription {
            get {
                return ResourceManager.GetString("NewtonsoftJsonIgnoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; doesn&apos;t use a JsonIgnoreAttribute.
        /// </summary>
        internal static string NewtonsoftJsonIgnoreMessageFormat {
            get {
                return ResourceManager.GetString("NewtonsoftJsonIgnoreMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonIgnoreAttribute to property (Newtonsoft.Json).
        /// </summary>
        internal static string NewtonsoftJsonIgnoreTitle {
            get {
                return ResourceManager.GetString("NewtonsoftJsonIgnoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property should have JsonPropertyAttribute..
        /// </summary>
        internal static string NewtonsoftJsonPropertyNameDescription {
            get {
                return ResourceManager.GetString("NewtonsoftJsonPropertyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; doesn&apos;t use a JsonPropertyAttribute.
        /// </summary>
        internal static string NewtonsoftJsonPropertyNameMessageFormat {
            get {
                return ResourceManager.GetString("NewtonsoftJsonPropertyNameMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonPropertyAttribute to property.
        /// </summary>
        internal static string NewtonsoftJsonPropertyNameTitle {
            get {
                return ResourceManager.GetString("NewtonsoftJsonPropertyNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonPropertyNameAttributes to all properties in class..
        /// </summary>
        internal static string SystemTextJsonClassDescription {
            get {
                return ResourceManager.GetString("SystemTextJsonClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; doesn&apos;t use JsonPropertyNameAttributes on every property.
        /// </summary>
        internal static string SystemTextJsonClassMessageFormat {
            get {
                return ResourceManager.GetString("SystemTextJsonClassMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all Properties in a class have a JsonPropertyNameAttribute.
        /// </summary>
        internal static string SystemTextJsonClassTitle {
            get {
                return ResourceManager.GetString("SystemTextJsonClassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonIgnore to property..
        /// </summary>
        internal static string SystemTextJsonIgnoreDescription {
            get {
                return ResourceManager.GetString("SystemTextJsonIgnoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; doesn&apos;t use a JsonIgnoreAttribute.
        /// </summary>
        internal static string SystemTextJsonIgnoreMessageFormat {
            get {
                return ResourceManager.GetString("SystemTextJsonIgnoreMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonIgnoreAttribute to property (System.Text.Json).
        /// </summary>
        internal static string SystemTextJsonIgnoreTitle {
            get {
                return ResourceManager.GetString("SystemTextJsonIgnoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property should have JsonPropertyNameAttribute..
        /// </summary>
        internal static string SystemTextJsonPropertyNameDescription {
            get {
                return ResourceManager.GetString("SystemTextJsonPropertyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; doesn&apos;t use a JsonPropertyNameAttribute.
        /// </summary>
        internal static string SystemTextJsonPropertyNameMessageFormat {
            get {
                return ResourceManager.GetString("SystemTextJsonPropertyNameMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JsonPropertyNameAttribute to property.
        /// </summary>
        internal static string SystemTextJsonPropertyNameTitle {
            get {
                return ResourceManager.GetString("SystemTextJsonPropertyNameTitle", resourceCulture);
            }
        }
    }
}
